# Импорт библиотек

In [1]:
import pandas as pd
import numpy as np
import json
import os

In [3]:
result_list = {'Заголовок': [], 'Название компании': [], 'Описание': [], 'Рейтинг': [], 'Категория': [], 'Дата': [], 'Текст': []}
brak = []

In [5]:
json_files = os.listdir(r'C:\Users\kazyh\OneDrive\Рабочий стол\Data2')
json_files

['Cybersport.Metaratings.json',
 'ESforce Holding.json',
 'Gett.json',
 'Goose Gaming.json',
 'MMA.Metaratings.json',
 'skillbox.json',
 'Vinci Agency.json',
 'Гэллэри Сервис.json',
 'Здоровье.ру.json',
 'Иннотех.json',
 'Проект по использованию технологий компьютерного зрения на базе искусственного интеллекта для анализа медицинских изображений.json',
 'Промобот.json',
 'Студия Артемия Лебедева.json',
 'Федерация креативных индустрий.json']

In [9]:
company_data = []
with open(r'C:\Users\kazyh\OneDrive\Рабочий стол\CompanyDate\company.json', 'r', encoding='UTF-8') as file:
    company_data = json.load(file)

In [11]:
path = r'C:\Users\kazyh\OneDrive\Рабочий стол\Data2'

In [13]:
for json_file in json_files:
    with open(f'{path}/{json_file}', 'r', encoding='UTF-8') as file:
        try:    
            data_json = json.load(file)
            for item in range(len(data_json['refs'])):
                if data_json['refs'][item] == None:
                    continue
                    
                if data_json['info'] != None:
                    result_list['Заголовок'].append(None)
                    result_list['Рейтинг'].append(data_json['info']['rate'])
                    result_list['Категория'].append(', '.join(data_json['info']['industries']))
                else:
                    [result_list[i].append(None) for i in ['Заголовок', 'Рейтинг', 'Категория']]
                    
                for company_item in company_data:
                    if company_item['company_name'] == json_file.replace('.json', ''):
                        result_list['Название компании'].append(company_item['company_name'])
                        result_list['Описание'].append(company_item['description'])
                date_pub = f'{data_json['refs'][item][1]['day']} {data_json['refs'][item][1]['month']} {data_json['refs'][item][1]['time']}'
                result_list['Дата'].append(date_pub)
                text_pub = ''.join(data_json['refs'][item][0]).replace('\n', ' ').replace('\t', ' ').replace('\xa0', ' ').replace('\u200e', ' ').replace('\r', ' ')
                result_list['Текст'].append(text_pub)
        except Exception as e:
            print(e)
            brak.append(json_file)

In [19]:
df = pd.DataFrame(data=result_list)

In [23]:
df

,Заголовок,Название компании,Описание,Рейтинг,Категория,Дата,Текст
0,None,Cybersport.Metaratings,7 декабря состоялась церемония награждения лау...,NaN,None,8 декабря 09:30,7 декабря состоялась церемония награждения лау...
1,None,ESforce Holding,7 декабря состоялась церемония награждения лау...,NaN,None,8 декабря 09:30,7 декабря состоялась церемония награждения лау...
2,None,ESforce Holding,7 декабря состоялась церемония награждения лау...,NaN,None,29 июля 13:50,Из совместного исследования издателя компьютер...
3,None,ESforce Holding,7 декабря состоялась церемония награждения лау...,NaN,None,9 июля 09:33,По статистике The Esports Observer за I полови...
4,None,ESforce Holding,7 декабря состоялась церемония награждения лау...,NaN,None,11 апреля 12:43,Компании SuperData Research и PayPal провели с...
...,...,...,...,...,...,...,...
1107,None,Федерация креативных индустрий,Фонд содействия инновациям проводит приём заяв...,NaN,None,30 января 10:43,"Привет, Хабр! Представляю вашему вниманию пере..."
1108,None,Федерация креативных индустрий,Фонд содействия инновациям проводит приём заяв...,NaN,None,24 апреля 12:37,Источник «Умный человек не делает все ошибки с...
1109,None,Федерация креативных индустрий,Фонд содействия инновациям проводит приём заяв...,NaN,None,12 октября 14:09,"Привет, Хабр! Сегодня мы решили поделиться с с..."
1110,None,Федерация креативных индустрий,Фонд содействия инновациям проводит приём заяв...,NaN,None,4 сентября 16:44,"Привет! Меня зовут Никита Бокарев, я креативны..."
1111,None,Федерация креативных индустрий,Фонд содействия инновациям проводит приём заяв...,NaN,None,5 июня 06:21,Компетентностая модель — это попытка создания ...

In [25]:
df[df['Категория'].notnull()]

,Заголовок,Название компании,Описание,Рейтинг,Категория,Дата,Текст
146,None,skillbox,Сравниваем традиционный способ извлечения знач...,113.82,"Веб-разработка, Дизайн и юзабилити, Реклама и ...",29 марта 17:20,Сравниваем традиционный способ извлечения знач...
147,None,skillbox,Сравниваем традиционный способ извлечения знач...,113.82,"Веб-разработка, Дизайн и юзабилити, Реклама и ...",28 марта 15:01,Издание «Ведомости» поговорило с участниками р...
148,None,skillbox,Сравниваем традиционный способ извлечения знач...,113.82,"Веб-разработка, Дизайн и юзабилити, Реклама и ...",14 марта 13:41,"Александр Нозик, физик и программист, руководи..."
149,None,skillbox,Сравниваем традиционный способ извлечения знач...,113.82,"Веб-разработка, Дизайн и юзабилити, Реклама и ...",3 марта 10:24,Всем привет! В конце 21-го года состоялся пер...
150,None,skillbox,Сравниваем традиционный способ извлечения знач...,113.82,"Веб-разработка, Дизайн и юзабилити, Реклама и ...",1 марта 19:33,1 марта VK запустила информационную кампанию в...
...,...,...,...,...,...,...,...
858,None,Иннотех,На Хабр Карьере запустилась карьерная неделя —...,47.73,"Веб-разработка, Программное обеспечение, Веб-с...",14 июня 10:06,Подборка мероприятий на неделю Blockchain Z-D...
859,None,Иннотех,На Хабр Карьере запустилась карьерная неделя —...,47.73,"Веб-разработка, Программное обеспечение, Веб-с...",10 июня 13:33,"ГК «Иннотех» — группа компаний, которая занима..."
860,None,Иннотех,На Хабр Карьере запустилась карьерная неделя —...,47.73,"Веб-разработка, Программное обеспечение, Веб-с...",23 ноября 10:17,Подборка мероприятий на неделю HolyJS 2020 Mo...
861,None,Иннотех,На Хабр Карьере запустилась карьерная неделя —...,47.73,"Веб-разработка, Программное обеспечение, Веб-с...",1 августа 06:46,Специалисты Центрального аэрогидродинамическог...
862,None,Иннотех,На Хабр Карьере запустилась карьерная неделя —...,47.73,"Веб-разработка, Программное обеспечение, Веб-с...",22 апреля 02:18,В юбилейный день космонавтики в Москве открыла...

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1112 entries, 0 to 1111
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Заголовок          0 non-null      object
 1   Название компании  1112 non-null   object
 2   Описание           1112 non-null   object
 3   Рейтинг            293 non-null    float64
 4   Категория          293 non-null    object
 5   Дата               1112 non-null   object
 6   Текст              1112 non-null   object
dtypes: float64(1), object(6)
memory usage: 60.9+ KB